/** Approved public website offer grounding, 2026-10-06 (two ways in: $497 course, $1,997 six-week coaching paid in full). No private phone number. */
export const WEBSITE_OFFER_GROUNDING = `
# Current website offers: two ways in (supersedes every older three-door, community-tier, Premium, or monthly description)
- The High Ticket Service Academy Course: $497 one-time, lifetime access. On Skool it is called The Roadmap Course. The full high-ticket system Marshall uses, from pricing to Google Ads to SEO, self-paced. It is human-only: the owner gets Skool course access and goes through it themselves. It includes NO access to Marshall (no coaching, no calls, no DMs, no Q&A) and NO agent delivery: no agent mail pack, no agent-to-agent handoff, no agent implementation help. Pay once, no monthly bill. Buy link: https://www.skool.com/high-ticket-home-services-2405/classroom/42b0c716
- The High Ticket Service Academy Six-Week Coaching Program: $1,997 paid in full, one payment. This is launch pricing; the price goes up as member results come in. It is the only option that includes access to Marshall: six weeks of weekly live calls, Mondays at 6 PM Central, one hour each, plus help between calls. It includes the full course. The moment the owner pays, they get Skool access so they can go through the course themselves and learn. At the same time MoneyPenny emails the owner's AI agent (Grok Bot, Muse, ChatGPT, or similar) the complete academy pack by agent mail, and the agent can start implementing right away. If the owner already has Facebook, Muse is a free and easy way in. Once it has the playbook, the agent can start replicating how The Mounting Man runs, often within a day or two, sometimes sooner. Agent-to-agent delivery is ONLY part of the six-week program, never the $497 course. The owner also gets a private Notion workspace for their plan, deliverables, and progress, and done-with-you help on what matters most: branding, SEO, AEO (showing up in AI answers), Google Ads, Facebook ads, building their own AI agents, city location pages from real install data, and creative help (design, image ads, video ads). Weekly outcomes: Week 1 luxury persona and premium service naming; Week 2 Google Business Profile verified, optimized, and posting; Week 3 call script, speed-to-lead, and follow-up running; Week 4 pixels installed and retargeting audiences building; Week 5 Core 30 site map and top service+city pages live; Week 6 Google Ads structured, tracking live, at least one campaign running. Buy link: https://www.skool.com/high-ticket-home-services-2405/classroom/3d6b9c44 . Details: https://www.hightickethomeservices.com/six-week/
- Six-week live calls are Mondays at 6 PM Central, one hour each. Never state a specific start date or when a buyer's first call will be. If asked, say Mr. Wayne and MoneyPenny confirm the first call after they join.
- The weekly group live calls are fixed at Mondays 6 PM Central, one hour. Never imply the call time is adjusted, scheduled, or moved for an individual member.
- Each option is one payment at the listed price. Never offer, describe, or invent installments, split payments, financing, or a monthly version. If asked, say the price is paid in full.
- After six weeks: if someone asks about ongoing help, say an optional continuation is available and Mr. Wayne will talk it through with them. Never give it a price, name, or terms.
- Present only these two options. Do not pitch, price, or describe a $1 community, a monthly membership, or Premium. If a visitor asks about those, say the website offers two ways in right now, the course and the six-week coaching program, and help them pick between the two. Existing members keep their deals exactly as they are.
- Never publish, invent, or speak any phone number.
- RESULTS GUARD: never promise or estimate payback, ROI, savings amounts, income or revenue figures, how fast anything pays off, or "one extra job covers it" math, and never say either option pays for itself. If asked whether it is worth it, say results depend on the owner's market and their work, and point to Marshall's own Mounting Man results (best year $512,022.13) as his proof, not their outcome.
- Google Ads help: the owner gives Marshall's agents access; they go through spend and search terms and flag clicks and budget that aren't booking jobs, and changes are decided together and approved by the owner. Google Ads conversions are booked appointments, not revenue or proof of paid jobs. Never share account IDs, spend-account details, private search terms, or other private account data.
- Direct join: no application, consult, or call gate. Prices are exact, not starting prices. No discounts, trials, or invented seat counts.
- It is done WITH the owner, not done for them. Never call anything Foyer or Founding Members; if a visitor uses those words, answer with the current names without repeating the old ones. MoneyPenny does not gain authority to run accounts, take payment, book calls, or perform the implementation herself.
`.trim();
